/*
 * Stub rdk_nl80211_hal.h for wifi-emulator build.
 * The real header is platform-specific (TCXB8) and not needed for emulation.
 * Only provides enums/defines - function declarations are in wifi_hal_priv.h.
 */
#ifndef RDK_NL80211_HAL_H
#define RDK_NL80211_HAL_H

/* Platform flags */
#ifndef PLATFORM_FLAGS_UPDATE_WIPHY_ON_PRIMARY
#define PLATFORM_FLAGS_UPDATE_WIPHY_ON_PRIMARY 0
#endif

#ifndef PLATFORM_FLAGS_CONTROL_PORT_FRAME
#define PLATFORM_FLAGS_CONTROL_PORT_FRAME 0
#endif

#ifndef PLATFORM_FLAGS_SET_BSS
#define PLATFORM_FLAGS_SET_BSS 0
#endif

/* OUI */
#define OUI_COMCAST 0x001018

/* RDK Vendor NL80211 subcmds */
enum {
    RDK_VENDOR_NL80211_SUBCMD_SET_STATION_EMU = 1,
    RDK_VENDOR_NL80211_SUBCMD_SET_STATION_LIST_EMU,
    RDK_VENDOR_NL80211_SUBCMD_SET_WIPHY_TEMP,
    RDK_VENDOR_NL80211_SUBCMD_SET_SURVEY_EMU,
    RDK_VENDOR_NL80211_SUBCMD_SET_RADIO_INFO,
    RDK_VENDOR_NL80211_SUBCMD_SET_AMSDU_CONFIG,
};

/* RDK Vendor NL80211 standards */
enum {
    RDK_VENDOR_NL80211_STANDARD_NONE = 0,
    RDK_VENDOR_NL80211_STANDARD_A,
    RDK_VENDOR_NL80211_STANDARD_B,
    RDK_VENDOR_NL80211_STANDARD_G,
    RDK_VENDOR_NL80211_STANDARD_N,
    RDK_VENDOR_NL80211_STANDARD_AC,
    RDK_VENDOR_NL80211_STANDARD_AD,
    RDK_VENDOR_NL80211_STANDARD_AX,
    RDK_VENDOR_NL80211_STANDARD_BE,
};

/* RDK Vendor NL80211 channel widths */
enum {
    RDK_VENDOR_NL80211_CHAN_WIDTH_20 = 0,
    RDK_VENDOR_NL80211_CHAN_WIDTH_40,
    RDK_VENDOR_NL80211_CHAN_WIDTH_80,
    RDK_VENDOR_NL80211_CHAN_WIDTH_160,
    RDK_VENDOR_NL80211_CHAN_WIDTH_320,
};

/* AMSDU TID max */
#define RDK_VENDOR_NL80211_AMSDU_TID_MAX 8

/* RDK Vendor attributes - survey info */
enum {
    RDK_VENDOR_ATTR_SURVEY_INFO = 1,
    RDK_VENDOR_ATTR_SURVEY_INFO_FREQUENCY,
    RDK_VENDOR_ATTR_SURVEY_INFO_NOISE,
    RDK_VENDOR_ATTR_SURVEY_INFO_RADAR_NOISE,
    RDK_VENDOR_ATTR_SURVEY_INFO_MAX_RSSI,
    RDK_VENDOR_ATTR_SURVEY_INFO_NON_80211_NOISE,
    RDK_VENDOR_ATTR_SURVEY_INFO_CHAN_UTIL,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_ACTIVE,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_BUSY,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_BUSY_TX,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_BUSY_RX,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_BUSY_RX_SELF,
    RDK_VENDOR_ATTR_SURVEY_INFO_TIME_EXT_BUSY,
};

/* RDK Vendor attributes - radio info */
enum {
    RDK_VENDOR_ATTR_RADIO_INFO = 100,
    RDK_VENDOR_ATTR_RADIO_INDEX,
    RDK_VENDOR_ATTR_RADIO_INFO_NOISE_FLOOR,
    RDK_VENDOR_ATTR_RADIO_INFO_CHANNEL_UTILIZATION,
    RDK_VENDOR_ATTR_RADIO_INFO_ACTIVITY_FACTOR,
    RDK_VENDOR_ATTR_RADIO_INFO_CARRIERSENSE_THRESHOLD,
    RDK_VENDOR_ATTR_RADIO_INFO_RETRANSMISSION,
    RDK_VENDOR_ATTR_RADIO_INFO_MAX_NOISE_FLOOR,
    RDK_VENDOR_ATTR_RADIO_INFO_MIN_NOISE_FLOOR,
    RDK_VENDOR_ATTR_RADIO_INFO_MEDIAN_NOISE_FLOOR,
    RDK_VENDOR_ATTR_RADIO_INFO_STATS_START_TIME,
    RDK_VENDOR_ATTR_RADIO_INFO_BYTES_SENT,
    RDK_VENDOR_ATTR_RADIO_INFO_BYTES_RECEIVED,
    RDK_VENDOR_ATTR_RADIO_INFO_PACKETS_SENT,
    RDK_VENDOR_ATTR_RADIO_INFO_PACKETS_RECEIVED,
    RDK_VENDOR_ATTR_RADIO_INFO_ERRORS_SENT,
    RDK_VENDOR_ATTR_RADIO_INFO_ERRORS_RECEIVED,
    RDK_VENDOR_ATTR_RADIO_INFO_DISCARD_PACKETS_SENT,
    RDK_VENDOR_ATTR_RADIO_INFO_DISCARD_PACKETS_RECEIVED,
    RDK_VENDOR_ATTR_RADIO_INFO_PLCP_ERRORS_COUNT,
    RDK_VENDOR_ATTR_RADIO_INFO_FCS_ERRORS_COUNT,
    RDK_VENDOR_ATTR_RADIO_INFO_INVALID_MAC_COUNT,
    RDK_VENDOR_ATTR_RADIO_INFO_PACKETS_OTHER_RECEIVED,
};

/* RDK Vendor attributes - station info */
enum {
    RDK_VENDOR_ATTR_STA_INFO = 200,
    RDK_VENDOR_ATTR_STA_NUM,
    RDK_VENDOR_ATTR_STA_INFO_ASSOC_NUM,
    RDK_VENDOR_ATTR_STA_INFO_MLD_MAC,
    RDK_VENDOR_ATTR_STA_INFO_OPER_CHANNEL_BW,
    RDK_VENDOR_ATTR_STA_INFO_OPER_STANDARD,
    RDK_VENDOR_ATTR_STA_INFO_RX_BITRATE_LAST,
    RDK_VENDOR_ATTR_STA_INFO_RX_BYTES64,
    RDK_VENDOR_ATTR_STA_INFO_RX_ERRORS,
    RDK_VENDOR_ATTR_STA_INFO_RX_PACKETS64,
    RDK_VENDOR_ATTR_STA_INFO_RX_RATE_MAX,
    RDK_VENDOR_ATTR_STA_INFO_RX_RETRIES,
    RDK_VENDOR_ATTR_STA_INFO_SIGNAL_AVG,
    RDK_VENDOR_ATTR_STA_INFO_SNR,
    RDK_VENDOR_ATTR_STA_INFO_SPATIAL_STREAM_NUM,
    RDK_VENDOR_ATTR_STA_INFO_STA_FLAGS,
    RDK_VENDOR_ATTR_STA_INFO_TX_BITRATE_LAST,
    RDK_VENDOR_ATTR_STA_INFO_TX_BYTES64,
    RDK_VENDOR_ATTR_STA_INFO_TX_ERRORS,
    RDK_VENDOR_ATTR_STA_INFO_TX_FAILED_RETRIES,
    RDK_VENDOR_ATTR_STA_INFO_TX_FRAMES,
    RDK_VENDOR_ATTR_STA_INFO_TX_PACKETS_ACK,
    RDK_VENDOR_ATTR_STA_INFO_TX_RATE_MAX,
    RDK_VENDOR_ATTR_STA_INFO_TX_RETRIES,
    RDK_VENDOR_ATTR_STA_INFO_TX_RETRIES_PERCENT,
};

/* RDK Vendor attributes - misc */
enum {
    RDK_VENDOR_ATTR_MAC = 300,
    RDK_VENDOR_ATTR_VAP_INDEX,
    RDK_VENDOR_ATTR_AMSDU_TIDS,
    RDK_VENDOR_ATTR_EMU_ENABLE,
    RDK_VENDOR_ATTR_WIPHY_TEMP,
};

#endif /* RDK_NL80211_HAL_H */
